### ISSUE TITLE
Graph: Put arrowtips on edges

### ISSUE THREAD

**Issue by valentinoli** [com-480-data-visualization/com-480-project-vizcachas#3]
Make edges appear as directed, with arrow tips

One example:
http://bl.ocks.org/fancellu/2c782394602a93921faff74e594d1bb1

**Comment by valentinoli** [comment]
Now we've got the edges, but we need to fix that weird bug where the lines start from the center of the circle. Don't know why this happens.

**Comment by Oceanos1** [comment]
Same for me, I've been investigating for days and can't manage to find what's the difference between others code and ours
