### ISSUE TITLE
Bug: Graph tooltip overflows

### ISSUE THREAD

**Issue by plechoss** [com-480-data-visualization/com-480-project-vizcachas#33]
There is a bug with the graph tooltip positioning. It is always positioned on the right but it overflows the container if it is too far on the right. We should probably position in to the left if the node is on the right side of the screen.

**Comment by valentinoli** [comment]
The same goes for the position on the vertical axis. It should now be fixed.

**Comment by valentinoli** [comment]
The same goes for the position on the vertical axis. It should now be fixed.
